#!/bin/bash

echo "========================================="
echo "   GitHub Commit Explorer - Docker Setup "
echo "========================================="
echo ""

# 1. Prompt for Custom IP for the Frontend payload
read -p "Enter the IP address or domain this app will be hosted on (e.g. 192.168.1.100 or localhost): " CUSTOM_IP
if [ -z "$CUSTOM_IP" ]; then
    CUSTOM_IP="localhost"
    echo "No IP provided. Defaulting to 'localhost'."
fi

# 2. Prompt for Custom Ports
read -p "Enter the Backend Port (default 3001): " BACKEND_PORT
BACKEND_PORT=${BACKEND_PORT:-3001}

read -p "Enter the Frontend Port (default 80): " FRONTEND_PORT
FRONTEND_PORT=${FRONTEND_PORT:-80}

VITE_URL="http://${CUSTOM_IP}:${BACKEND_PORT}/api"
echo "Frontend API Endpoint Will Be Set To: $VITE_URL"
echo ""

# 3. Prompt for GitHub Personal Access Token
read -s -p "Enter your Secure GitHub Personal Access Token (PAT): " GITHUB_TOKEN
echo ""
if [ -z "$GITHUB_TOKEN" ]; then
    echo "WARNING: No token provided! The API might rate-limit you heavily or fail on private repos."
else
    echo "GitHub Token Captured."
fi
echo ""

# 3. Write variables to backend/.env
echo "Generating configurations..."
cat << EOF > backend/.env
# Autogenerated by setup.sh
PORT=3001
GITHUB_TOKEN=${GITHUB_TOKEN}
EOF

# 4. Write variables to root .env for docker-compose to ingest universally
cat << EOF > .env
# Autogenerated by setup.sh (For Docker Compose)
GITHUB_TOKEN=${GITHUB_TOKEN}
FRONTEND_VITE_API_URL=${VITE_URL}
FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
EOF
echo ".env files successfully written!"
echo ""

# 5. Build and deploy using Docker Compose
echo "Starting Docker Build Process..."
docker-compose build --no-cache
docker-compose up -d

echo ""
echo "========================================="
echo " Deployment Successful! "
echo " Frontend Live At: http://${CUSTOM_IP}:${FRONTEND_PORT}"
echo " Backend Live At:  http://${CUSTOM_IP}:${BACKEND_PORT}"
echo "========================================="
